# This is a TOML document for go-sns-manager-api.
title = "gin-learn-todo_dev_conf"

[api_server]
listen_addr = ":8888"
debug= true
timezone = "PRC"

[mysql]
[mysql.sns]
addr = "root:lookfor@Dny8$@tcp(127.0.0.1:3306)/sns?parseTime=true&loc=Local&charset=utf8"
max_open_conns = 3
max_idle_conns = 2
max_life_time = 3600


[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0


