# This is a TOML document for go-sns-manager-api.
title = "gin-learn-todo_dev_conf"

[api_server]
app_name     = "gin-learn-todo"
listen_addr = ":8888"
debug	= true

timezone = "PRC"

[log_config]
log_path = "/Users/lukun/data/apps/works/go-apps/src/gin-learn-todo/logs"


[db]
[db.sns]
host = "127.0.0.1"
db_name = "sns"
user = "root"
pwd = "lookfor@Dny8$"
port = "3306"
charset = "utf8mb4"
max_open_conns = 3
max_idle_conns = 2
max_life_time = 3600


[redis]
host = "127.0.0.1"
pwd  = ""
port = "6379"

max_active_conns = 30
max_idle_conns = 5
idle_timeout_second = 180

pool_size = 30
dial_timeout_millisecond = 50
read_timeout_millisecond = 100
write_timeout_millisecond = 100

