# This is a TOML document for go-sns-manager-api.
title = "gin-learn-todo_prod_conf"

[app]
listen_addr = ":8888"
debug = true
timezone = "PRC"
env = "prod"

# 业务appid
app_id = "1"

[mysql]
[mysql.sns]
addr = "root:123456@tcp(127.0.0.1:3306)/sns?parseTime=true&loc=Local&charset=utf8"
max_open_conns = 3
max_idle_conns = 2
max_life_time = 3600


[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0

max_active_conns = 30
max_idle_conns = 5
idle_timeout_second = 180

pool_size = 30
dial_timeout_millisecond = 50
read_timeout_millisecond = 100
write_timeout_millisecond = 100

[sentry]
dsn = "http://4f8175c96d4c439abaa7337f52ff5927@sentry.itech8.run/2"