# This is a TOML document for go-sns-manager-api.
title = "gin-learn-todo_prod_conf"

[app]
addr = ":8888"
debug = true
timezone = "PRC"
env = "prod"
# 业务appid
app_id = "1"

[sentry]
env = "test,prod"
dsn = "http://4f8175c96d4c439abaa7337f52ff5927@sentry.itech8.run/2"

# mysql 集群 支持集群一主多从
[db]
default="sns"   # 默认集群
[db.clusters.sns.master]
dns = "root:123456@tcp(127.0.0.1:3306)/sns?parseTime=true&loc=Local&charset=utf8"
max_open_conns = 3
max_idle_conns = 2
max_life_time = 10
#[[db.clusters.sns.slaves]]
#addr = "root:123456@tcp(127.0.0.1:3306)/sns?parseTime=true&loc=Local&charset=utf8"
#max_open_conns = 3
#max_idle_conns = 2
#max_life_time = 10

#[db.clusters.tools.master]
#dns = "root:123456@tcp(127.0.0.1:3306)/tools?parseTime=true&loc=Local&charset=utf8"
#max_open_conns = 3
#max_idle_conns = 2
#max_life_time = 10
#[[db.clusters.tools.slaves]]


[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0

max_active_conns = 30
max_idle_conns = 5
idle_timeout_second = 180

pool_size = 30
dial_timeout_millisecond = 50
read_timeout_millisecond = 100
write_timeout_millisecond = 100

[etcd]
app = "gin-learn-todo"
env = "prod"
etcd_endpoints = "127.0.0.1:2379"
etcd_user = "peanut"
etcd_password = "123456"
etcd_prefix = "/app/config/"

[logger]
encoding = "json"
path = "./error.log"
level = "debug"