// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-01-14 14:16:18.872272 +0800 CST m=+10.557057023

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "花生",
            "email": "peanut@itech8.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/v1/oauth": {
            "post": {
                "description": "用于微信,QQ等各第三方平台的联合登录",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "第三方登录接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "oauth code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/auth.UserInfo"
                        }
                    }
                }
            }
        },
        "/auth/v1/user/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用于微信,QQ等各第三方平台的联合登录",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/auth.UserInfo"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "保存用户信息（目前支持头像昵称保存）",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "保存用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "头像地址",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "昵称",
                        "name": "nickname",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/auth.UserInfo"
                        }
                    }
                }
            }
        },
        "/v1/achievement/claim": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回用户账户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "领取成就奖励"
                ],
                "summary": "领取成就奖励接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.AchievementClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.AchievementClaimResponse"
                        }
                    }
                }
            }
        },
        "/v1/achievement/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回成就列表数据，包含状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "成就列表"
                ],
                "summary": "成就列表接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resource.AchievementItem"
                            }
                        }
                    }
                }
            }
        },
        "/v1/activity/spring2020/active": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "春节活动开关状态(code==0 为开，否则为关(msg为activity is not active))",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "春节活动开关状态"
                ],
                "summary": "春节活动开关状态接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/v1/activity/spring2020/info": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取春节活动信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取春节活动信息"
                ],
                "summary": "获取春节活动信息接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.Spring2020InfoResponse"
                        }
                    }
                }
            }
        },
        "/v1/activity/spring2020/join": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "加入春节活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "加入春节活动"
                ],
                "summary": "加入春节活动接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.Spring2020JoinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.Spring2020JoinResponse"
                        }
                    }
                }
            }
        },
        "/v1/activity/spring2020/lottery": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "春节活动抽奖",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "春节活动抽奖"
                ],
                "summary": "春节活动抽奖接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.Spring2020LotteryResponse"
                        }
                    }
                }
            }
        },
        "/v1/building/done": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "完成模型",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "完成模型"
                ],
                "summary": "完成模型接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.BuildingDoneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.BuildingDoneResponse"
                        }
                    }
                }
            }
        },
        "/v1/building/info": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取模型信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取模型信息"
                ],
                "summary": "获取模型信息接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.BuildingInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.BuildingItem"
                        }
                    }
                }
            }
        },
        "/v1/building/unlock": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "模型解锁后返回用户账户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型解锁"
                ],
                "summary": "模型解锁接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.BuildingUnlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.BuildingUnlockResponse"
                        }
                    }
                }
            }
        },
        "/v1/city/item/detail": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回城市详情数据，包含模型列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "城市详情"
                ],
                "summary": "城市详情接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.CityItemDetailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "城市建筑模型列表列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resource.BuildingItem"
                            }
                        }
                    }
                }
            }
        },
        "/v1/city/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回城市列表数据，包含状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "城市列表"
                ],
                "summary": "城市列表接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "城市列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resource.CityListItem"
                            }
                        }
                    }
                }
            }
        },
        "/v1/settle/coins/claim": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "结算领取金币",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "结算领取金币"
                ],
                "summary": "结算领取金币接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.SettleClaimCoinsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.SettleClaimCoinsResponse"
                        }
                    }
                }
            }
        },
        "/v1/tips/get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取提示",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取提示"
                ],
                "summary": "获取提示接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.GetTipResponse"
                        }
                    }
                }
            }
        },
        "/v1/tips/use": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "使用提示",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用提示"
                ],
                "summary": "使用提示接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.UseTipResponse"
                        }
                    }
                }
            }
        },
        "/v1/topic/item/detail": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回主题详情数据，包含模型列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "主题详情"
                ],
                "summary": "主题详情接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.TopicItemDetailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "建筑模型列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resource.BuildingItem"
                            }
                        }
                    }
                }
            }
        },
        "/v1/topic/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "主题列表"
                ],
                "summary": "主题列表接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "主题列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resource.TopicListItem"
                            }
                        }
                    }
                }
            }
        },
        "/v1/user/base/info": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户基础信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户基础信息"
                ],
                "summary": "获取用户基础信息接口（包含金币和飞机票）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "平台",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/resource.GetUserBasicInfoResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.UserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "openid": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.LotteryResult": {
            "type": "object",
            "properties": {
                "type": {
                    "description": "中奖类型 coin lego",
                    "type": "string"
                },
                "value": {
                    "description": "中奖值",
                    "type": "integer"
                }
            }
        },
        "resource.AchievementClaimRequest": {
            "type": "object",
            "properties": {
                "achievement_id": {
                    "description": "成就id",
                    "type": "integer"
                }
            }
        },
        "resource.AchievementClaimResponse": {
            "type": "object",
            "properties": {
                "balance_infos": {
                    "description": "账户余额信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wallet.BalanceInfo"
                    }
                }
            }
        },
        "resource.AchievementItem": {
            "type": "object",
            "properties": {
                "building_num": {
                    "description": "建筑模型总数量",
                    "type": "integer"
                },
                "color_img": {
                    "description": "彩色图片",
                    "type": "string"
                },
                "done_num": {
                    "description": "已完成建筑模型数量",
                    "type": "integer"
                },
                "done_time": {
                    "description": "达成时间",
                    "type": "string"
                },
                "gray_img": {
                    "description": "灰色图片",
                    "type": "string"
                },
                "id": {
                    "description": "成就id",
                    "type": "integer"
                },
                "name": {
                    "description": "名字",
                    "type": "string"
                },
                "rank": {
                    "description": "已完成状态时，显示的排名",
                    "type": "integer"
                },
                "reward_type": {
                    "description": "奖励类型",
                    "type": "string"
                },
                "reward_value": {
                    "description": "奖励数量",
                    "type": "integer"
                },
                "status": {
                    "description": "0 未完成 1 已完成未领取奖励 2 已领取奖励",
                    "type": "integer"
                }
            }
        },
        "resource.BuildingDoneRequest": {
            "type": "object",
            "properties": {
                "building_id": {
                    "description": "模型id",
                    "type": "integer"
                }
            }
        },
        "resource.BuildingDoneResponse": {
            "type": "object",
            "properties": {
                "reward_ad_remain_times": {
                    "description": "广告翻倍剩余次数",
                    "type": "integer"
                },
                "reward_factor": {
                    "description": "看广告可翻倍数",
                    "type": "integer"
                },
                "reward_type": {
                    "description": "奖励类型",
                    "type": "string"
                },
                "reward_value": {
                    "description": "奖励值",
                    "type": "integer"
                }
            }
        },
        "resource.BuildingInfoRequest": {
            "type": "object",
            "properties": {
                "building_id": {
                    "description": "模型id",
                    "type": "integer"
                }
            }
        },
        "resource.BuildingItem": {
            "type": "object",
            "properties": {
                "ad_factor": {
                    "description": "看广告可翻倍数",
                    "type": "integer"
                },
                "block_num": {
                    "description": "零件个数",
                    "type": "integer"
                },
                "block_path": {
                    "description": "零件网络路径",
                    "type": "string"
                },
                "cover_done": {
                    "description": "已完成封面图",
                    "type": "string"
                },
                "cover_lock": {
                    "description": "未解锁封面图url",
                    "type": "string"
                },
                "desc": {
                    "description": "描述",
                    "type": "string"
                },
                "id": {
                    "description": "建筑模型id",
                    "type": "integer"
                },
                "name": {
                    "description": "建筑模型名",
                    "type": "string"
                },
                "reward_type": {
                    "description": "奖励类型（完成模型）coin / diamond",
                    "type": "string"
                },
                "reward_value": {
                    "description": "奖励值（完成模型）",
                    "type": "integer"
                },
                "save_img": {
                    "description": "保存的图片",
                    "type": "string"
                },
                "share_img": {
                    "description": "分享的图片",
                    "type": "string"
                },
                "status": {
                    "description": "状态 0 未解锁 1 解锁未完成 2 已完成未领取奖励 3 已领取奖励",
                    "type": "integer"
                },
                "tags": {
                    "description": "标签，逗号分隔",
                    "type": "string"
                },
                "unlock_type": {
                    "description": "解锁类型",
                    "type": "string"
                },
                "unlock_value": {
                    "description": "如果解锁类型为金币或钻石，那此字段为具体的金币和钻石数量",
                    "type": "integer"
                }
            }
        },
        "resource.BuildingUnlockRequest": {
            "type": "object",
            "properties": {
                "building_id": {
                    "description": "模型id",
                    "type": "integer"
                }
            }
        },
        "resource.BuildingUnlockResponse": {
            "type": "object",
            "properties": {
                "balance_infos": {
                    "description": "账户余额信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wallet.BalanceInfo"
                    }
                }
            }
        },
        "resource.CityItemDetailRequest": {
            "type": "object",
            "properties": {
                "city_id": {
                    "description": "城市id",
                    "type": "integer"
                }
            }
        },
        "resource.CityListItem": {
            "type": "object",
            "properties": {
                "city_id": {
                    "description": "@城市id",
                    "type": "integer"
                },
                "color_back": {
                    "description": "彩色背景url或路径",
                    "type": "string"
                },
                "gray_back": {
                    "description": "灰色背景url或路径",
                    "type": "string"
                },
                "icon_done": {
                    "description": "完成图标url",
                    "type": "string"
                },
                "icon_lock": {
                    "description": "未解锁图标url",
                    "type": "string"
                },
                "lock_status": {
                    "description": "是否鎖定 0 否 1 是",
                    "type": "integer"
                },
                "music": {
                    "description": "音乐",
                    "type": "string"
                },
                "name": {
                    "description": "城市名字",
                    "type": "string"
                }
            }
        },
        "resource.FriendItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                }
            }
        },
        "resource.GetTipResponse": {
            "type": "object",
            "properties": {
                "remain_time": {
                    "description": "剩余冷却时间(单位s)",
                    "type": "integer"
                },
                "remain_times": {
                    "description": "剩余激励视频次数",
                    "type": "integer"
                }
            }
        },
        "resource.GetUserBasicInfoResponse": {
            "type": "object",
            "properties": {
                "balance_infos": {
                    "description": "账户余额信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wallet.BalanceInfo"
                    }
                }
            }
        },
        "resource.SettleClaimCoinsRequest": {
            "type": "object",
            "properties": {
                "building_id": {
                    "description": "建筑模型id",
                    "type": "integer"
                },
                "t": {
                    "description": "1 未看广告(普通领取) 2 已看广告（翻倍领取）",
                    "type": "integer"
                }
            }
        },
        "resource.SettleClaimCoinsResponse": {
            "type": "object",
            "properties": {
                "balance_infos": {
                    "description": "账户余额信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wallet.BalanceInfo"
                    }
                }
            }
        },
        "resource.Spring2020InfoResponse": {
            "type": "object",
            "properties": {
                "friend_list": {
                    "description": "好友列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resource.FriendItem"
                    }
                },
                "inviter": {
                    "description": "邀请人",
                    "type": "object",
                    "$ref": "#/definitions/resource.FriendItem"
                },
                "status": {
                    "description": "0 需邀请好友 1 完成邀请好友，待拼图 2 完成拼图未抽奖 3 完成抽奖",
                    "type": "integer"
                },
                "title": {
                    "description": "活动标题",
                    "type": "string"
                }
            }
        },
        "resource.Spring2020JoinRequest": {
            "type": "object",
            "properties": {
                "from": {
                    "description": "邀请人的uuid",
                    "type": "string"
                }
            }
        },
        "resource.Spring2020JoinResponse": {
            "type": "object",
            "properties": {
                "friend_list": {
                    "description": "好友列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resource.FriendItem"
                    }
                },
                "inviter": {
                    "description": "邀请人",
                    "type": "object",
                    "$ref": "#/definitions/resource.FriendItem"
                }
            }
        },
        "resource.Spring2020LotteryResponse": {
            "type": "object",
            "properties": {
                "balance_infos": {
                    "description": "账户余额信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wallet.BalanceInfo"
                    }
                },
                "lottery_result": {
                    "description": "中奖结果",
                    "type": "object",
                    "$ref": "#/definitions/model.LotteryResult"
                }
            }
        },
        "resource.TopicItemDetailRequest": {
            "type": "object",
            "properties": {
                "topic_id": {
                    "description": "主题id",
                    "type": "integer"
                }
            }
        },
        "resource.TopicListItem": {
            "type": "object",
            "properties": {
                "block_num": {
                    "description": "零件总数量",
                    "type": "integer"
                },
                "building_num": {
                    "description": "建筑模型数量",
                    "type": "integer"
                },
                "desc": {
                    "description": "详情描述",
                    "type": "string"
                },
                "done_cover": {
                    "description": "完成的封面",
                    "type": "string"
                },
                "lock_cover": {
                    "description": "未完成的封面",
                    "type": "string"
                },
                "progress": {
                    "description": "进度[0,100]",
                    "type": "integer"
                },
                "status": {
                    "description": "0 未完成 1 完成",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "topic_id": {
                    "description": "主题id",
                    "type": "integer"
                }
            }
        },
        "resource.UseTipResponse": {
            "type": "object"
        },
        "wallet.BalanceInfo": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost",
	BasePath:    "/api/",
	Schemes:     []string{},
	Title:       "Gin-learn-todo API",
	Description: "聚宝盆-服务端API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
