definitions:
  define.User:
    properties:
      age:
        type: integer
      astrology:
        type: string
      avatar:
        type: string
      create_time:
        type: integer
      id:
        type: integer
      medium:
        type: string
      nick_name:
        type: string
      passport:
        type: string
      phone:
        type: integer
      sex:
        type: integer
      source:
        type: string
      status:
        type: integer
      update_time:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /user/info/{id}:
    get:
      consumes:
      - application/json
      description: 单个用户详情
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户详情
          schema:
            $ref: '#/definitions/define.User'
      security:
      - ApiKeyAuth: []
      summary: 单个用户详情接口
      tags:
      - 后台API
swagger: "2.0"
